# SPDX-FileCopyrightText: 2025 wahl.chat
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

services:
  wahl-chat-frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
        - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
        - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - SITE_URL=${SITE_URL}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    image: wahl-chat-frontend:latest
    env_file:
      - .env
    restart: always
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.wahl-chat-frontend.rule=Host(`${TRAEFIK_ROUTER_HOST}`)'
      - "traefik.http.routers.wahl-chat-frontend.entrypoints=websecure"
      - "traefik.http.routers.wahl-chat-frontend.tls=true"
      - "traefik.http.routers.wahl-chat-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.wahl-chat-frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  traefik-public:
    name: ${TRAEFIK_PUBLIC_NETWORK}
    external: true

